In [26]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
import hvplot.pandas

In [27]:
#Load data 
file= "C:/Users/user/Desktop/U of T boot camp data analyst/Cryptocurrencies/new_iris_data.csv"
df_iris =pd.read_csv(file)
df_iris.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [28]:
import plotly.figure_factory as ff

In [29]:
#standarize data with StandardScaler
iris_scaled =StandardScaler().fit_transform(df_iris)
print(iris_scaled[0:5])

[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]]


In [30]:
# Initialize PCA model
pca = PCA(n_components=2)

In [31]:
# Get two principal components for the iris data.
df_iris_pca = pca.fit_transform(iris_scaled)

In [32]:
# Create the dendrogram
fig = ff.create_dendrogram(df_iris_pca, color_threshold=0)
fig.update_layout(width=800, height=500)
fig.show()


In [33]:
agg = AgglomerativeClustering(n_clusters=3)
model = agg.fit(df_iris_pca)

In [34]:
#Add a new class column to df_iris
df_iris_pca["class"] = model.labels_
df_iris_pca.head()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [35]:
#Plotting the clusters
df_iris_pca.hvplot.scatter(
    x="principal component 1",
    y="principal component 2",
    hover_cols=["class"],
    by="class",
)

AttributeError: 'numpy.ndarray' object has no attribute 'hvplot'